#! /bin/bash

mkdir -p ~/.schmokin

echo 'export PATH=~/.schmokin/:$PATH' >> ~/.profile

curl -sLo ~/.schmokin/schmokin "https://github.com/reaandrew/schmokin/releases/download/latest/schmokin"

chmod +x ~/.schmokin/schmokin

echo "To start using now run: source ~/.profile"
