#! /bin/bash

mkdir -p ~/.schmokin

echo 'export PATH=~/.schmokin/:$PATH' >> ~/.profile

curl -sLo ~/.schmokin/schmokin.tar.gz "https://github.com/reaandrew/schmokin/releases/download/latest/schmokin.tar.gz"

tar -xzvf ~/.schmokin/schmokin.tar.gz -C ~/.schmokin

chmod +x ~/.schmokin/schmokin

echo "To start using now run: source ~/.profile"
