#! /bin/sh
# file: examples/equality_test.sh

python schmokin_test_server.py >/dev/null 2>&1 /dev/null &
sleep 1
pid=$!  
ENDPOINT=http://localhost:40000
oneTimeTearDown(){
    kill $pid 2>/dev/null
}

# NOTE ABOUT ASSERTIONS
# ---------------------------------------------------------
# The following tests assert on the variable $? which
# is the return code of the previous command
# ---------------------------------------------------------

testAssertingOnStatusCode() {
    ./schmokin $ENDPOINT/simple -s 200
    assertEquals 0 $?
}

testAssertingOnStatusCode_Fails() {
    ./schmokin $ENDPOINT/simple -s 201
    assertEquals 1 $?
}

testAssertingEQ() {
    ./schmokin $ENDPOINT/simple --jq-expr '.status' --eq "UP"
    assertEquals 0 $?
}

testAssertingEQ_Fails() {
    ./schmokin $ENDPOINT/simple --jq-expr '.status' --eq "DOWN"
    assertEquals 1 $?
}

testAssertingGT() {
    ./schmokin $ENDPOINT/array --jq-expr '. | length' --gt 4
    assertEquals 0 $?
}

testAssertingGT_Fails() {
    ./schmokin $ENDPOINT/array --jq-expr '. | length' --gt 6
    assertEquals 1 $?
}


testAssertingGE_Equals() {
    ./schmokin $ENDPOINT/array --jq-expr '. | length' --ge 5
    assertEquals 0 $?
}

testAssertingGE_Greater() {
    ./schmokin $ENDPOINT/array --jq-expr '. | length' --ge 4
    assertEquals 0 $?
}

testAssertingGE_Fails() {
    ./schmokin $ENDPOINT/array --jq-expr '. | length' --ge 6
    assertEquals 1 $?
}

testAssertingLT() {
    ./schmokin $ENDPOINT/array --jq-expr '. | length' --lt 6
    assertEquals 0 $?
}

testAssertingLT_Fails() {
    ./schmokin $ENDPOINT/array --jq-expr '. | length' --lt 5
    assertEquals 1 $?
}

testAssertingLE_Equals() {
    ./schmokin $ENDPOINT/array --jq-expr '. | length' --le 5
    assertEquals 0 $?
}

testAssertingLE_Lesser() {
    ./schmokin $ENDPOINT/array --jq-expr '. | length' --le 6
    assertEquals 0 $?
}

testAssertingLE_Fails() {
    ./schmokin $ENDPOINT/array --jq-expr '. | length' --le 4
    assertEquals 1 $?
}


testAssertingMultipleTimes() {
    ./schmokin $ENDPOINT/array --jq-expr '. | length' --gt 4 -s 200
    assertEquals 0 $?
}

testAssertingOnResponseHeader(){
    ./schmokin $ENDPOINT/array --resp-header "Content-Type" --eq 'application/json'
    assertEquals 0 $?
}

testAssertingOnRequestHeader(){
    ./schmokin $ENDPOINT/array --req-header "Accept" --eq '*/*'
    assertEquals 0 $?
}

testAssertingOnContains(){
    ./schmokin $ENDPOINT/array --resp-header "Server" --contains 'Python'
    assertEquals 0 $?
}

# Load shUnit2.
. ./shunit2-2.1.7/shunit2

