#! /bin/sh
# file: examples/equality_test.sh

python schmokin_test_server.py >/dev/null 2>&1 /dev/null &
sleep 1
pid=$!  
ENDPOINT=http://localhost:40000
oneTimeTearDown(){
    kill $pid
}

# NOTE ABOUT ASSERTIONS
# ---------------------------------------------------------
# The following tests assert on the variable $? which
# is the return code of the previous command
# ---------------------------------------------------------

testAssertingOnStatusCode() {
    curl -vs $ENDPOINT/simple 2>&1 | \
        ./schmokin -s 200

    assertEquals 0 $?
}

testAssertingOnStatusCode_Fails() {
    curl -vs $ENDPOINT/simple 2>&1 | \
        ./schmokin -s 201

    assertEquals 1 $?
}

testAssertingEQ() {
    curl -vs $ENDPOINT/simple 2>&1 | \
        ./schmokin --jq-expr '.status' --eq "UP"

    assertEquals 0 $?
}

testAssertingEQ_Fails() {
    curl -vs $ENDPOINT/simple 2>&1 | \
        ./schmokin --jq-expr '.status' --eq "DOWN"

    assertEquals 1 $?
}

testAssertingGT() {
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --jq-expr '. | length' --gt 4

    assertEquals 0 $?
}

testAssertingGT_Fails() {
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --jq-expr '. | length' --gt 6

    assertEquals 1 $?
}


testAssertingGE_Equals() {
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --jq-expr '. | length' --ge 5

    assertEquals 0 $?
}

testAssertingGE_Greater() {
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --jq-expr '. | length' --ge 4

    assertEquals 0 $?
}

testAssertingGE_Fails() {
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --jq-expr '. | length' --ge 6

    assertEquals 1 $?
}

testAssertingLT() {
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --jq-expr '. | length' --lt 6

    assertEquals 0 $?
}

testAssertingLT_Fails() {
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --jq-expr '. | length' --lt 5

    assertEquals 1 $?
}

testAssertingLE_Equals() {
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --jq-expr '. | length' --le 5

    assertEquals 0 $?
}

testAssertingLE_Lesser() {
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --jq-expr '. | length' --le 6

    assertEquals 0 $?
}

testAssertingLE_Fails() {
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --jq-expr '. | length' --le 4

    assertEquals 1 $?
}


testAssertingMultipleTimes() {
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --jq-expr '. | length' --gt 4 \
        -s 200

    assertEquals 0 $?
}

testAssertingOnResponseHeader(){
    curl -vs $ENDPOINT/array 2>&1 | \
        ./schmokin --resp-header "Content-Type" \
            --eq 'application/json'

    assertEquals 0 $?
}

# Load shUnit2.
. ./shunit2-2.1.7/shunit2

